plugins:
  - jekyll-relative-links
title: "It's the little things"
description: "Things that makes the life of a windows admin easier"
logo: "images/gears.png"
show_downloads: false
google_analytics: abccd
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
theme: jekyll-theme-minimal